#ifndef TWL_OS_MACHINE_SETTING_JUMP_H_
#define TWL_OS_MACHINE_SETTING_JUMP_H_

#ifdef __cplusplus
extern "C" {
#endif

#ifdef SDK_TWL
#if defined(SDK_ARM9) || defined(SDK_PORT)

#include <nitro.h>

typedef enum OSTWLMSJumpDestination {
  OS_TWL_MACHINE_SETTING_PAGE_1 = 0,
  OS_TWL_MACHINE_SETTING_PAGE_2 = 2,
  OS_TWL_MACHINE_SETTING_PAGE_3 = 3,
  OS_TWL_MACHINE_SETTING_PAGE_4 = 4,
  OS_TWL_MACHINE_SETTING_APP_MANAGER = 5,
  OS_TWL_MACHINE_SETTING_WIRELESS_SW = 6,
  OS_TWL_MACHINE_SETTING_BRIGHTNESS = 7,
  OS_TWL_MACHINE_SETTING_USER_INFO = 8,
  OS_TWL_MACHINE_SETTING_DATE = 9,
  OS_TWL_MACHINE_SETTING_TIME = 10,
  OS_TWL_MACHINE_SETTING_ALARM = 11,
  OS_TWL_MACHINE_SETTING_TP_CALIBRATION = 12,
  OS_TWL_MACHINE_SETTING_LANGUAGE = 13,
  OS_TWL_MACHINE_SETTING_PARENTAL_CONTROL = 14,
  OS_TWL_MACHINE_SETTING_NETWORK_SETTING = 15,
  OS_TWL_MACHINE_SETTING_NETWORK_EULA = 16,
  OS_TWL_MACHINE_SETTING_NETWORK_OPTION = 17,
  OS_TWL_MACHINE_SETTING_COUNTRY = 18,
  OS_TWL_MACHINE_SETTING_SYSTEM_UPDATE = 19,
  OS_TWL_MACHINE_SETTING_SYSTEM_INITIALIZE = 20,
  OS_TWL_MACHINE_SETTING_MAX
} OSTWLMSJumpDestination;

BOOL OSi_JumpToMachineSetting(u8 dest);

BOOL OSi_JumpToEulaDirect(void);

BOOL OSi_JumpToApplicationManagerDirect(void);

BOOL OSi_JumpToNetworkSettngDirect(void);

BOOL OSi_JumpToCountrySettingDirect(void);

BOOL OSi_JumpToSystemUpdateDirect(void);

#endif /* SDK_ARM9 */
#endif /* SDK_TWL */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
