libtwl_libs = []
libtwl_prebuilt = []

subdir('camera')
subdir('card')
subdir('cp')
subdir('ctrdg')
subdir('demo')
subdir('dsp')
subdir('el')
subdir('env')
subdir('ext')
subdir('fs')
subdir('fx')
subdir('gx')
subdir('init')
subdir('math')
subdir('mb')
subdir('mi')
subdir('os')
subdir('prc')
subdir('pxi')
subdir('rtc')
subdir('scfg')
subdir('snd')
subdir('spi')
subdir('std')
subdir('stubs')
subdir('wbt')
subdir('wfs')
subdir('wm')
subdir('wvr')
subdir('wxc')

if (build_target != 'arm')
    subdir('sim')
    subdir('sim7')
endif