#ifndef _MB_PRIVATE_H_
#define _MB_PRIVATE_H_

#ifdef __cplusplus
extern "C" {
#endif

#if !defined(NITRO_FINALROM)

#endif

#define CALLBACK_WM_STATE 0

#include <nitro/types.h>
#include <nitro/wm.h>
#include <nitro/mb.h>
#include "mb_wm_base.h"
#include "mb_common.h"
#include "mb_block.h"
#include "mb_rom_header.h"
#include "mb_gameinfo.h"
#include "mb_fileinfo.h"
#include "mb_child.h"

#include "mb_cache.h"
#include "mb_task.h"

#ifdef PRINT_DEBUG
#define MB_OUTPUT(...) OS_TPrintf(__VA_ARGS__)
#define MB_DEBUG_OUTPUT(...)                                                   \
  MBi_DebugPrint(__FILE__, __LINE__, __FUNCTION__, __VA_ARGS__)

#else
#define MB_OUTPUT(...) ((void)0)
#define MB_DEBUG_OUTPUT(...) ((void)0)
#endif

#define MB_IPL_VERSION (0x0001)
#define MB_MAX_BLOCK 12288 // Max 12288 * 256 = 3.0 MB

#define MB_NUM_PARENT_INFORMATIONS 16 /* Maximum number of parents */

#define MB_SCAN_TIME_NORMAL WM_DEFAULT_SCAN_PERIOD
#define MB_SCAN_TIME_NORMAL_FOR_FAKE_CHILD 20
#define MB_SCAN_TIME_LOCKING 220

typedef struct MB_CommCommonWork {

  u32 sendbuf[MB_MAX_SEND_BUFFER_SIZE / sizeof(u32)] ATTRIBUTE_ALIGN(32);
  u32 recvbuf[MB_MAX_RECV_BUFFER_SIZE * MB_MAX_CHILD * 2 /
              sizeof(u32)] ATTRIBUTE_ALIGN(32);
  MBUserInfo user; // User information for this device
  u16 isMbInitialized;
  int block_size_max;
  BOOL start_mp_busy; /* WM_StartMP() is operating */
  BOOL is_started_ex; /* WM_StartParentEX() called */
  u8 padding[28];
} MB_CommCommonWork;

typedef struct MB_CommPWork {
  MB_CommCommonWork common;

  MBUserInfo childUser[MB_MAX_CHILD] ATTRIBUTE_ALIGN(4);
  u16 childversion[MB_MAX_CHILD]; // Child device version information (in
                                  // quantity equal to the number of child
                                  // devices)
  u32 childggid[MB_MAX_CHILD];    // Child device GGID (in quantity equal to the
                                  // number of child devices)
  MBCommPStateCallback
      parent_callback;              // Parent state callback function pointer
  int p_comm_state[MB_MAX_CHILD];   // Holds the state of each of the children
  u8 file_num;                      // Number of registered files
  u8 cur_fileid;                    // File number of the current file to send
  s8 fileid_of_child[MB_MAX_CHILD]; // File number that a child requested (-1
                                    // when there is no request)
  u8 child_num;                     // Number of entry children
  u16 child_entry_bmp;              // Child entry control bitmap
  MbRequestPieceBuf
      req_data_buf;            // Buffer for receiving child partition requests
  u16 req2child[MB_MAX_CHILD]; // The request to send to the child
  MBUserInfo
      childUserBuf; // Child information buffer for passing to the application

  struct {

    MBDownloadFileInfo dl_fileinfo;
    MBGameInfo game_info;
    MB_BlockInfoTable blockinfo_table;
    MBGameRegistry *game_reg;
    void *
        src_adr; //  The starting address of the boot image on the parent device
    u16 currentb;             // The current block
    u16 nextb;                // The next block to send
    u16 pollbmp;              // PollBitmap for sending data
    u16 gameinfo_child_bmp;   // The current bitmap member for updating the
                              // GameInfo
    u16 gameinfo_changed_bmp; // The bitmap member that was generated by a
                              // change for updating the GameInfo
    u8 active;
    u8 update;

    MBiCacheList *cache_list; /* Cache list */
    u32 *card_mapping;        /* CARD address for the start of each segment */

  } fileinfo[MB_MAX_FILE];

  BOOL useWvrFlag; // Flag indicating whether or not WVR is being used
  u8 padding2[20];

  u8 task_work[2 * 1024];
  MBiTaskInfo cur_task;

} MB_CommPWork;

typedef struct MB_CommCWork {
  MB_CommCommonWork common;

  WMBssDesc bssDescbuf ATTRIBUTE_ALIGN(32); // WMBssDesc backup
  MBDownloadFileInfo
      dl_fileinfo; // The DownloadFileInfo buffer of the child device
  MBCommCStateCallbackFunc
      child_callback; // The state callback function pointer of the child device
  int c_comm_state;   // The state of the child device
  int connectTargetNo; // The MbBeaconRecvStatus list number of the connection
                       // target
  u8 fileid;           // The requested file number
  u8 _padding1[1];
  u16 user_req;
  u16 got_block;   // The number of downloaded blocks
  u16 total_block; // The total number of blocks of the download file
  u8 recvflag[MB_MAX_BLOCK / 8]; // Flag that shows the block receive state
  MB_BlockInfoTable blockinfo_table;
  int last_recv_seq_no; // Sequence number of the block received previously
  u8 boot_end_flag; // Flag for determining whether MB termination by BOOT_READY
                    // is being processed
  u8 _padding2[15];
} MB_CommCWork;

extern MB_CommCommonWork *mbc;

#define pPwork ((MB_CommPWork *)mbc)

#define pCwork ((MB_CommCWork *)mbc)

#ifdef __cplusplus
}
#endif

#endif /*  _MB_PRIVATE_H_  */
