#ifndef TWL_HW_ARM9_MMAP_MAIN_H_
#define TWL_HW_ARM9_MMAP_MAIN_H_
#ifdef __cplusplus
extern "C" {
#endif

#define HW_MAIN_MEM_MAIN_SIZE 0x003e0000   // 3.875 MB
#define HW_MAIN_MEM_SUB_SIZE 0x0001f000    // 124 KB
#define HW_MAIN_MEM_SHARED_SIZE 0x00001000 // 4 KB

#define HW_MAIN_MEM_MAIN (HW_MAIN_MEM)
#define HW_MAIN_MEM_MAIN_END (HW_MAIN_MEM_MAIN + HW_MAIN_MEM_MAIN_SIZE)
#define HW_MAIN_MEM_SUB (HW_MAIN_MEM_SUB_END - HW_MAIN_MEM_SUB_SIZE)
#define HW_MAIN_MEM_SUB_END (HW_MAIN_MEM_EX_END - HW_MAIN_MEM_SHARED_SIZE)

#define HW_MAIN_MEM_SHARED (HW_MAIN_MEM_SHARED_END - HW_MAIN_MEM_SHARED_SIZE)
#define HW_MAIN_MEM_SHARED_END (HW_TWL_MAIN_MEM_END)

#define HW_MAIN_MEM_IM_SHARED_SIZE (HW_MAIN_MEM_SHARED_SIZE)
#define HW_MAIN_MEM_IM_SHARED                                                  \
  (HW_MAIN_MEM_IM_SHARED_END - HW_MAIN_MEM_IM_SHARED_SIZE)
#define HW_MAIN_MEM_IM_SHARED_END (HW_MAIN_MEM + 0x00800000)

#define HW_TWL_MAIN_MEM_MAIN_SIZE 0x00f80000   // 15.5 MB
#define HW_TWL_MAIN_MEM_SUB_SIZE 0x0007c000    // 496 KB
#define HW_TWL_MAIN_MEM_SHARED_SIZE 0x00004000 // 16 KB

#define HW_TWL_MAIN_MEM_MAIN (HW_TWL_MAIN_MEM)
#define HW_TWL_MAIN_MEM_MAIN_END                                               \
  (HW_TWL_MAIN_MEM_MAIN + HW_TWL_MAIN_MEM_MAIN_SIZE)
#define HW_TWL_MAIN_MEM_SUB (HW_TWL_MAIN_MEM_SUB_END - HW_TWL_MAIN_MEM_SUB_SIZE)
#define HW_TWL_MAIN_MEM_SUB_END (HW_TWL_MAIN_MEM_SHARED)
#define HW_TWL_MAIN_MEM_SHARED                                                 \
  (HW_TWL_MAIN_MEM_SHARED_END - HW_TWL_MAIN_MEM_SHARED_SIZE)
#define HW_TWL_MAIN_MEM_SHARED_END (HW_TWL_MAIN_MEM_END)

#define HW_MAIN_MEM_PARAMETER_BUF 0x02000000
#define HW_MAIN_MEM_PARAMETER_BUF_SIZE 0x4000
#define HW_MAIN_MEM_PARAMETER_BUF_END                                          \
  (HW_MAIN_MEM_PARAMETER_BUF + HW_MAIN_MEM_PARAMETER_BUF_SIZE)

#define HW_MAIN_MEM_DEBUGGER_OFFSET 0x700000
#define HW_MAIN_MEM_DEBUGGER_SIZE 0x080000
#define HW_MAIN_MEM_DEBUGGER (HW_MAIN_MEM + HW_MAIN_MEM_DEBUGGER_OFFSET)
#define HW_MAIN_MEM_DEBUGGER_END                                               \
  (HW_MAIN_MEM_DEBUGGER + HW_MAIN_MEM_DEBUGGER_SIZE)

#define HW_TWL_MAIN_MEM_DEBUGGER_OFFSET                                        \
  (HW_TWL_MAIN_MEM_DEBUGGER - HW_TWL_MAIN_MEM)
#define HW_TWL_MAIN_MEM_DEBUGGER_SIZE 0x0c0000
#define HW_TWL_MAIN_MEM_DEBUGGER 0x0df00000
#define HW_TWL_MAIN_MEM_DEBUGGER_END                                           \
  (HW_TWL_MAIN_MEM_DEBUGGER + HW_TWL_MAIN_MEM_DEBUGGER_SIZE)

#ifdef __cplusplus
} /* extern "C" */
#endif
#endif /* TWL_HW_ARM9_MMAP_MAIN_H_ */
