#ifndef TWL_HW_COMMON_MMAP_PARAMETER_H_
#define TWL_HW_COMMON_MMAP_PARAMETER_H_
#ifdef __cplusplus
extern "C" {
#endif

#define HW_PARAM_DELIVER_ARG_OFS 0x000
#define HW_PARAM_DELIVER_ARG_SIZE 0x300
#define HW_PARAM_DELIVER_ARG                                                   \
  (HW_MAIN_MEM_PARAMETER_BUF + HW_PARAM_DELIVER_ARG_OFS)
#define HW_PARAM_DELIVER_ARG_END                                               \
  (HW_PARAM_DELIVER_ARG + HW_PARAM_DELIVER_ARG_SIZE)

#define HW_PARAM_DELIVER_ARG_TITLEID_OFS 0x0
#define HW_PARAM_DELIVER_ARG_GAMECODE_OFS 0x8
#define HW_PARAM_DELIVER_ARG_MAKERCODE_OFS 0xc
#define HW_PARAM_DELIVER_ARG_DATASIZE_OFS 0xe
#define HW_PARAM_DELIVER_ARG_FLAG_OFS 0x10
#define HW_PARAM_DELIVER_ARG_DATA_OFS 0x11

#define HW_PARAM_DELIVER_ARG_TITLEID                                           \
  (HW_MAIN_MEM_PARAMETER_BUF + HW_PARAM_DELIVER_ARG_TITLEID_OFS)
#define HW_PARAM_DELIVER_ARG_GAMECODE                                          \
  (HW_MAIN_MEM_PARAMETER_BUF + HW_PARAM_DELIVER_ARG_GAMECODE_OFS)
#define HW_PARAM_DELIVER_ARG_MAKERCODE                                         \
  (HW_MAIN_MEM_PARAMETER_BUF + HW_PARAM_DELIVER_ARG_MAKERCODE_OFS)
#define HW_PARAM_DELIVER_ARG_DATASIZE                                          \
  (HW_MAIN_MEM_PARAMETER_BUF + HW_PARAM_DELIVER_ARG_DATASIZE_OFS)
#define HW_PARAM_DELIVER_ARG_FLAG                                              \
  (HW_MAIN_MEM_PARAMETER_BUF + HW_PARAM_DELIVER_ARG_FLAG_OFS)
#define HW_PARAM_DELIVER_ARG_DATA                                              \
  (HW_MAIN_MEM_PARAMETER_BUF + HW_PARAM_DELIVER_ARG_DATA_OFS)

#define HW_PARAM_LAUNCH_PARAM_OFS 0x300
#define HW_PARAM_LAUNCH_PARAM_SIZE 0x100
#define HW_PARAM_LAUNCH_PARAM                                                  \
  (HW_MAIN_MEM_PARAMETER_BUF + HW_PARAM_LAUNCH_PARAM_OFS)
#define HW_PARAM_LAUNCH_PARAM_END                                              \
  (HW_PARAM_LAUNCH_PARAM + HW_PARAM_LAUNCH_PARAM_SIZE)

#define HW_PARAM_TWL_SETTINGS_DATA_DEFAULT HW_PARAM_LAUNCH_PARAM_END
#define HW_PARAM_TWL_SETTINGS_DATA (OS_GetSystemWork()->preloadParameterAddr)
#define HW_PARAM_TWL_SETTINGS_DATA_SIZE 0x1e0
#define HW_PARAM_TWL_SETTINGS_DATA_END                                         \
  (OS_GetSystemWork()->preloadParameterAddr + HW_PARAM_TWL_SETTINGS_DATA_SIZE)

#define HW_PARAM_WIRELESS_FIRMWARE_DATA HW_PARAM_TWL_SETTINGS_DATA_END
#define HW_PARAM_WIRELESS_FIRMWARE_DATA_SIZE 0x20
#define HW_PARAM_WIRELESS_FIRMWARE_DATA_END                                    \
  (HW_PARAM_WIRELESS_FIRMWARE_DATA + HW_PARAM_WIRELESS_FIRMWARE_DATA_SIZE)

#define HW_PARAM_TWL_HW_NORMAL_INFO HW_PARAM_WIRELESS_FIRMWARE_DATA_END
#define HW_PARAM_TWL_HW_NORMAL_INFO_SIZE 0x20
#define HW_PARAM_TWL_HW_NORMAL_INFO_END                                        \
  (HW_PARAM_TWL_HW_NORMAL_INFO + HW_PARAM_TWL_HW_NORMAL_INFO_SIZE)

#define HW_PARAM_TWL_RESERVED_AREA HW_PARAM_TWL_HW_NORMAL_INFO_END
#define HW_PARAM_TWL_RESERVED_AREA_SIZE 0x39e0
#define HW_PARAM_TWL_RESERVED_AREA_END                                         \
  (HW_PARAM_TWL_RESERVED_AREA + HW_PARAM_TWL_RESERVED_AREA_SIZE)

#ifdef __cplusplus
} /* extern "C" */
#endif
#endif /* TWL_HW_COMMON_MMAP_PARAMETER_H_ */
